### ISSUE TITLE
unable to generate images with batch size >1

### ISSUE THREAD

**Issue by sunnyyangyangyang** [DenOfEquity/Hunyuan-DiT-for-webUI#2]
if I set batch size >1, webui return the following error message:
Traceback (most recent call last):
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\webui_forge_cu121_torch21\webui\extensions\Hunyuan-DiT-for-webUI\scripts\hunyuan_DiT_diffusers.py", line 414, in predict
    output = pipe(
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\diffusers\pipelines\hunyuandit\pipeline_hunyuandit.py", line 833, in __call__
    noise_pred = self.transformer(
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\webui_forge_cu121_torch21\system\python\lib\site-packages\diffusers\models\transformers\hunyuan_transformer_2d.py", line 489, in forward
    encoder_hidden_states = torch.where(text_embedding_mask, encoder_hidden_states, self.text_embedding_padding)
RuntimeError: The size of tensor a (2) must match the size of tensor b (8) at non-singleton dimension 0

**Comment by DenOfEquity** [comment]
Thanks for report.
Updated, including a fix for this, tested with diffusers 0.29.1 and 0.29.2.
