### ISSUE TITLE
Generate Error

### ISSUE THREAD

**Issue by ZZ-Zero** [DenOfEquity/Hunyuan-DiT-for-webUI#4]
webui return error message:

Startup time: 43.7s (prepare environment: 3.4s, launcher: 0.3s, import torch: 5.4s, initialize shared: 0.3s, other imports: 0.2s, load scripts: 3.9s, initialize google blockly: 7.1s, create ui: 3.5s, gradio launch: 18.6s, app_started_callback: 0.6s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 95.83% GPU memory (23539.00 MB) to load weights, and use 4.17% GPU memory (1024.00 MB) to do matrix computation.
Traceback (most recent call last):
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "E:\webui_forge_cu121_torch231\webui\extensions\Hunyuan-DiT-for-webUI\scripts\hunyuan_DiT_diffusers.py", line 227, in predict
    tokenizer = BertTokenizer.from_pretrained(
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\transformers\tokenization_utils_base.py", line 2132, in from_pretrained
    resolved_config_file = cached_file(
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\transformers\utils\hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\huggingface_hub\file_download.py", line 1011, in _hf_hub_download_to_cache_dir
    _download_to_tmp_and_move(
  File "E:\webui_forge_cu121_torch231\webui\modules_forge\patch_basic.py", line 86, in patched_download_to_tmp_and_move
    return original_download_to_tmp_and_move(incomplete_path, destination_path, url_to_download, proxies, headers, expected_size, filename, force_download)
  File "E:\webui_forge_cu121_torch231\system\python\lib\site-packages\huggingface_hub\file_download.py", line 1533, in _download_to_tmp_and_move
    with incomplete_path.open("ab") as f:
  File "pathlib.py", line 1119, in open
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\models\\diffusers\\models--Tencent-Hunyuan--HunyuanDiT-Diffusers\\blobs\\c57897ebb275499b3c6d5284f1187860f86741e6.incomplete'

![1733131086900](https://github.com/user-attachments/assets/1c8219d4-46cb-4db0-a6b7-4a17c9870a23)

**Comment by DenOfEquity** [comment]
I've seen this error in a few places recently, seems like a dependency update changed how saving of model downloads is handled.
Updated extension.
